### ISSUE TITLE
Unable to run docker container

### ISSUE THREAD

**Issue by stdavis** [agrc/gis.utah.gov#243]
## Issue description

When I run `docker-compose up` I get the following error message:

```
~/Documents/Projects/website (master $%) $ docker-compose up
Starting gis.utah.gov
Attaching to gis.utah.gov
gis.utah.gov | Using i18n 0.7.0
gis.utah.gov | Using json 1.8.3
gis.utah.gov | Using minitest 5.9.1
gis.utah.gov | Using thread_safe 0.3.5
gis.utah.gov | Using addressable 2.4.0
gis.utah.gov | Using coffee-script-source 1.10.0
gis.utah.gov | Using execjs 2.7.0
gis.utah.gov | Using colorator 1.1.0
gis.utah.gov | Using ffi 1.9.14
gis.utah.gov | Using multipart-post 2.0.0
gis.utah.gov | Using forwardable-extended 2.6.0
gis.utah.gov | Using gemoji 2.1.0
gis.utah.gov | Using net-dns 0.8.0
gis.utah.gov | Using public_suffix 1.5.3
gis.utah.gov | Using sass 3.4.22
gis.utah.gov | Using rb-fsevent 0.9.7
gis.utah.gov | Using kramdown 1.11.1
gis.utah.gov | Using liquid 3.0.6
gis.utah.gov | Using mercenary 0.3.6
gis.utah.gov | Using rouge 1.11.1
gis.utah.gov | Using safe_yaml 1.0.4
gis.utah.gov | Using jekyll-feed 0.5.1
gis.utah.gov | Using mini_portile2 2.1.0
gis.utah.gov | Using pkg-config 1.1.7
gis.utah.gov | Using jekyll-paginate 1.1.0
gis.utah.gov | Using jekyll-sitemap 0.10.0
gis.utah.gov | Using minima 1.2.0
gis.utah.gov | Using unicode-display_width 1.1.1
gis.utah.gov | Using bundler 1.12.5
gis.utah.gov | Using tzinfo 1.2.2
gis.utah.gov | Using coffee-script 2.4.1
gis.utah.gov | Using ethon 0.9.1
gis.utah.gov | Using rb-inotify 0.9.7
gis.utah.gov | Using faraday 0.9.2
gis.utah.gov | Using pathutil 0.14.0
gis.utah.gov | Using jekyll-sass-converter 1.3.0
gis.utah.gov | Using nokogiri 1.6.8
gis.utah.gov | Using terminal-table 1.7.3
gis.utah.gov | Using activesupport 4.2.7
gis.utah.gov | Using jekyll-coffeescript 1.0.1
gis.utah.gov | Using typhoeus 0.8.0
gis.utah.gov | Using listen 3.0.6
gis.utah.gov | Using sawyer 0.7.0
gis.utah.gov | Using html-pipeline 2.4.2
gis.utah.gov | Using jekyll-watch 1.5.0
gis.utah.gov | Using octokit 4.3.0
gis.utah.gov | Using jekyll 3.2.1
gis.utah.gov | Using github-pages-health-check 1.2.0
gis.utah.gov | Using jekyll-gist 1.4.0
gis.utah.gov | Using jekyll-github-metadata 2.0.2
gis.utah.gov | Using jekyll-mentions 1.2.0
gis.utah.gov | Using jekyll-redirect-from 0.11.0
gis.utah.gov | Using jekyll-seo-tag 2.0.0
gis.utah.gov | Using jemoji 0.7.0
gis.utah.gov | Using github-pages 96
gis.utah.gov | Bundle complete! 1 Gemfile dependency, 55 gems now installed.
gis.utah.gov | Use `bundle show [gemname]` to see where a bundled gem is installed.
gis.utah.gov | /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup': You have already activated json 2.0.2, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
gis.utah.gov |  from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
gis.utah.gov |  from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
gis.utah.gov |  from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
gis.utah.gov |  from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
gis.utah.gov |  from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<main>'
gis.utah.gov | sh: can't kill pid 41: No such process
gis.utah.gov exited with code 1
```

I ended up getting it to run using [this suggestion](https://github.com/jekyll/docker/issues/121#issuecomment-244603795). I'm guessing that I have some gem dependency conflicts?

**Comment by steveoh** [comment]
Sorry about that. I knew about this issue and have been deleting the Gemfile before running docker. The gemfile is recommended by our host netlify. I have not spent the time to fool with it as it seems like a package management issue. 

> You have already activated json 2.0.2, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

I too think the problem is what Azizure [mentions in that issue](https://github.com/jekyll/docker/issues/121#issuecomment-244779330)
